server:
  port: 8080

spring:
  application:
    name: planforge-api

  datasource:
    url: jdbc:h2:mem:planforge
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework.security: DEBUG